Feature/armor progression
chocolate-edition/Chocolate-Edition pull request #205
Opened 2023-12-15 23:57 UTC by GildedToxin

Diamond -> Netherite -> Dark metal -> Etherium/Enderium/Adamantite-> Ignitium

Heavy/Adamantite - less move speed, more knock back resistance, more health, more armor, more toughness, Less attack damage

Normal/Enderium - Armor up, Toughness up

Light/Etherium - Less health, less armor, less tough, More attack damage

Ignitium - more armor, more tougness, more health, more attack

2023-12-16 20:38 UTC, Jonah-Hansen requested changes
- theres an empty `armor_upgrades.zs` file in `/upgrading` I assume can be deleted.

- `amethyst_armor.zs` is all by itself in `/modstats` not sure if it should be moved into `/armor_progression` or just stay 

- should probably remove `test.zs` in `/armour_progression`


is it possible to modify the "when on body/legs/feet/head" attributes text so that similar stat changes are actually combined? ei. adamantite chestplate: "+2.5 armor, +8 armor" to just say +10.5 armor? 

or if not can we add some sort of other description text to explain the differences between the endgame pieces? I know we'll probably explain it in the quest book but its nice to hover over them in jei and see the differences there.

2023-12-16 20:38 UTC, Jonah-Hansen commented on overrides/scripts/modstats/armor_progression/neptunium_armor.zs
> +<item:aquaculture:neptunium_boots>.anyDamage().addGlobalAttributeModifier(<attribute:minecraft:generic.armor_toughness>, "Nerf_Dark_Metal_Boots_Toughness", 0.5, AttributeOperation.ADDITION, [<constan
attribute modifier names are Dark Metal here should be neptunium

2023-12-18 04:16 UTC, Jonah-Hansen requested changes
adding uuids fixed the issue of combining stat changes! please take a look at `/utils/AttributeIds` and add the remaining uuids. then we can use `AttributeIds.boots` etc in place of the uuid string. this solves the bad practice of having "magic strings" in our code!

please apply the uuid method to all the adjusted armors.

2023-12-18 04:19 UTC, GildedToxin commented
I'm like half way through em
didnt even realize that it was the same for all of them 0_o
this makes my life easier ig
but I question the time I spent
thank you none the less

2023-12-18 05:14 UTC, GildedToxin commented
I did it for all tools stats while I was at it

2023-12-18 19:09 UTC, Jonah-Hansen approved these changes
tested looks great! 

full adamantite is VERY slow.. I know people will generally mix armor pieces but if someone did want to be a full tank before 16 eyes, its almost unplayable with the speed reduction. 
would love to hear other opinions!

2023-12-18 19:38 UTC, GildedToxin commented
Very much agreed with the adamantite being slow - I wasn't really sure how slow to make it
I intended players to use other means to balance out the speed reduction, such as speed potions, beacon, and running shoes (or mix and match the armor like you said) - also if they are in the end, they have elyra which will be there main mode of movement
I could also give the armor more health as way to balance out the heavy speed loss
I've played 4 hours, so im not really sure how much health is `worth it` to players
I could also always just cut down on the speed and call it a day

2023-12-18 19:43 UTC, Jonah-Hansen commented
I vote just cut down on speed reduction by 25-50% of what it currently is. by late game everyone has speed boost items anyways so it just feels like a pretty heavy nerf. I think 4 extra hearts with a full set is pretty good.

2023-12-18 20:34 UTC, GildedToxin commented
rn it removes 80% move speed, ill knock down to 60%/50%
when you says 4 hearts do you mean for full hearts? or 4 halfs which make 2 full hearts (what the armor has rn)?

2023-12-18 20:41 UTC, Jonah-Hansen commented
tbh I thought it was 4 full. tough to decide. 2 full doesn't seem like much when considering ghast eye but also 4 full is probably a lot. maybe just leave it as as and we can reevaluate after playing with it for real

2023-12-19 01:04 UTC, RichPrune commented
gaming

2023-12-19 01:15 UTC, GildedToxin commented
gaming but no approval 😞

2023-12-19 18:52 UTC, merged