added one seed/crop type
chocolate-edition/Chocolate-Edition pull request #223
Opened 2024-01-09 16:50 UTC by RUsami

Added Elevibloom seed to the Crop quest

2024-01-09 17:20 UTC, RUsami commented
Actually Updated a bunch of quest (agriculture), can we merge the two commit together ?

2024-01-09 18:35 UTC, Jonah-Hansen approved these changes

2024-01-09 18:42 UTC, Jonah-Hansen requested changes

2024-01-09 18:42 UTC, Jonah-Hansen commented on overrides/config/ftbquests/quests/chapters/all_things_food.snbt
> +				}
these "<<<<<<< Updated upstream" lines are remenants of git merges, try removing it but double check that elevibloom seeds and aloe kernals still show up properly

2024-01-09 18:44 UTC, Jonah-Hansen commented
> Actually Updated a bunch of quest (agriculture), can we merge the two commit together ?

having multiple commits is totally fine. generally what we want is 
   1 commit = only the changes necessary for one small change/feature
   1 pull request = a collection of related commits

2024-01-11 20:52 UTC, Jonah-Hansen commented
@RUsami so this chapter is being deleted with 1.5.4 rework. you'll have to add these to the crop quest in the `Quests` chapter instead after #224 is merged, or branch off that one to make the change.

2024-01-11 20:52 UTC, closed without merging

2024-01-11 21:07 UTC, RUsami commented
Actually, I think all the changes here are already in the Christi Big ftbquest config changes ? 
Sorry for not saying it earlier

2024-01-11 21:10 UTC, Jonah-Hansen commented
> Actually, I think all the changes here are already in the Christi Big ftbquest config changes ? Sorry for not saying it earlier

I think you're right! It's all good then