Decreased enderman spawns
chocolate-edition/Chocolate-Edition pull request #272
Opened 2024-01-20 19:19 UTC by GildedToxin

decreased spawn rates of blastling, watchling, snareling, and end_enderman

closes #217

2024-01-20 23:52 UTC, RUsami requested changes
They spawn not enough now x) can you up their spawn rate a tad bit ?

2024-01-21 00:08 UTC, RUsami requested changes
can you up their spawnrates a bit more again ? x)))

2024-01-21 00:58 UTC, RUsami approved these changes
85% suppremacy

2024-01-21 01:00 UTC, Jonah-Hansen approved these changes

2024-01-21 01:01 UTC, merged