full changelog of all stuffs i changed so far and that need changing
chocolate-edition/Chocolate-Edition pull request #286
Opened 2024-01-21 21:35 UTC by RichPrune

1. Remove enig graves, dun gear, soulbound, respawn animals, incendium, terralith, spawn balance utility, fins and tails, goodall, straw golem, inv hud, smooth swapping, just enough advancements, chunk pregenerator
	2. Removed unnecessary and ugly resource packs
	3. Updated enlightend, cataclysm, CnC, Wayvf, easy npc, BiC
	4. Add galosphere, tectonic, void fog, brazier, hts treechop, cluttered, multimine, archaeology api, configurable keep inv, lets do bakery, atmospheric,
	5. Disabled biome bosses datapack temporarily again since SBU's removal means they no longer spawn, added back recipes to craft their summons, will make long term solutions soon
	6. Questbook overhaul (temporary version)
	7. Fix controls by setting all vanilla keys to default, and all mod keys to default UNLESS they conflict in which case I changed the less important key to shift or ctrl+
	8. Set default shader options to be potato
	9. Changed loading backgrounds
	10. Fixed parcool once and for all and removed stamina bar since its useless
	11. Fixed roll ui
	12. Buffed netherite monstrositys spd x2, atk x2, def x1.5, ignis atk x2 def x1.5, harbinger x1.5, void worm hp 1.5->x2, spd x1.6, atk *1.6, ender dragon atk x2, wither atk x1.5 spd x1.2, mut wither skelly spd x1.5 atk x1.5 kbr x2, mut blaze spd x1.5 atk x1.5, spiritcaller spd x1.5, magispeller hpx2 atkx1.5, leviathan atk x1.5, rosalyne kbr x1.5, capt cornelia kbr x1.5 hp x1.5 atk x1.5, warped mosco spd x1.5 atk x1.5, mut shulker atk x1.5, corrupted champion atk x1.8 spd x1.5, ender guardian atk x2, prisnautilus spd x1.5 atk x2, colossus spd x1.5, huntsman atk x1.5, queen bee atk x1.5
	13. Updated cataclysm
	14. Fix broken quest items
	15. Removed nightmare stalker from expert mode exclusive >:)
	16. First person model off by default
	17. Reenabled glow caves
	18. Fix menu buttons
	19. Spawn with quest book
	20. Echo/flamarangs break spawners
	21. Buffed max health increase from each food group being 80%+ from 1->2 hearts per group, and an extra 2 if all non sugar groups are 80%+
	22. Blast furnaces now smelt raw ore
	23. Fixed underminer bs
	24. Added ancient remnant and BOMD bosses to health regain list and farsighted mobs
	25. Added warden and other minibosses to farsighted mobs
	26. Fixed chess pieces spawning as loot
	27. Removed OLG from base rps

	Todo
	1. Find the resource pack with the Jei descs
	2. Keybinds in yosby should apply
	3. Backpacks should be craftable and not require bundles and og recipe should be disabled
	4. Rename galosphere Silver to aluminum 5.

2024-01-23 00:44 UTC, RichPrune commented
gaming

2024-01-23 01:10 UTC, Jonah-Hansen commented
I added new issues for the 2 todo items listed

2024-01-23 01:11 UTC, Jonah-Hansen commented
22. was fixed by #201

2024-01-23 01:14 UTC, Jonah-Hansen commented on overrides/config/bosshealthregain-common.toml
>  	#Radius to check around player who died for bosses to regain health. Default 16. Value between 0 and 256
not sure why github doesnt highlight it properly but the firrence between these two arrays is 

"cataclysm:ancient_remnant", "bosses_of_mass_destruction:lich", "bosses_of_mass_destruction:gauntlet", "bosses_of_mass_destruction:void_blossom", "bosses_of_mass_destruction:obsidilith",

2024-01-23 01:15 UTC, Jonah-Hansen commented on overrides/config/doapi/recipebook.json5
is this do api a new mod that was added?

2024-01-23 01:25 UTC, GildedToxin reviewed
24, 25, and 26 seem good, minus the double warden ofc

2024-01-23 01:25 UTC, GildedToxin commented on overrides/scripts/loot-changes/remove/tabletop.zs
> -loot.modifiers.removeByModId("tabletopcraft");
26 is good

2024-01-23 01:25 UTC, GildedToxin commented on overrides/defaultconfigs/farsightedmobs-server.toml
> +	mobFollowRangeOverrides = ["mutantmonsters:mutant_skeleton,96","mutantmonsters:mutant_zombie,96","mutantmonsters:mutant_creeper,96","mutantmonsters:mutant_enderman,96","mutantmore:mutant_blaze,96","
minecraft warden is here 2 times

2024-01-23 01:26 UTC, Jonah-Hansen requested changes
please list the mods that were added or removed and include the manifest and modlist from a profile export to reflect these changes!

2024-01-23 01:26 UTC, Jonah-Hansen commented on overrides/config/voidfog-client.toml
wasnt voidfog removed? please delete the config file

2024-01-23 01:26 UTC, Jonah-Hansen commented on overrides/mods/memoryleakfix-forge-1.17+-1.1.2.jar
why did you delete these mod files?

2024-01-23 01:35 UTC, Jonah-Hansen commented
also, wasnt the underminer issue fixed by editing a datapack? if so that datapack should be uploaded on drive or something. really we should have all zips required stored somewhere for easy download

2024-01-23 16:54 UTC, RichPrune commented on overrides/mods/memoryleakfix-forge-1.17+-1.1.2.jar
mods folder is uploaded to drive i deleted the folder cuz it had all the mods

2024-01-23 16:54 UTC, RichPrune commented on overrides/config/voidfog-client.toml
its not removed

2024-01-23 16:58 UTC, RichPrune commented
> please list the mods that were added or removed and include the manifest and modlist from a profile export to reflect these changes!

mods r in mods folder on drive and I already did in changelog, why do I need to upload manifest and modlist those auto generate upon export

2024-01-23 22:22 UTC, Jonah-Hansen commented on overrides/config/voidfog-client.toml
it is, you just never check github https://github.com/chocolate-edition/Chocolate-Edition/pull/252

2024-01-23 22:29 UTC, RUsami commented on overrides/config/doapi/recipebook.json5
Yes, it's for making the bakery mod work ^^

2024-01-23 22:30 UTC, RUsami commented on overrides/config/voidfog-client.toml
Christi put it back but lowered the fog. During beta testing we will see how it goes

2024-01-23 22:30 UTC, Jonah-Hansen commented on overrides/mods/memoryleakfix-forge-1.17+-1.1.2.jar
but if we try to use this as a profile import, these mods will be missing. 

github should contain everything needed so that we can simply zip the folder and use it as a profile import. (minus the .zips for datapacks but I'm working on a solution.)

wouldn't it be much nicer to be able to create a new instance knowing everything in it was properly synced with what all the other devs have without needing to downloading multiple things from different places?

please do a profile export and commit the mods included in that.

2024-01-25 05:23 UTC, GildedToxin commented on overrides/defaultconfigs/farsightedmobs-server.toml
> +	mobFollowRangeOverrides = ["mutantmonsters:mutant_skeleton,96","mutantmonsters:mutant_zombie,96","mutantmonsters:mutant_creeper,96","mutantmonsters:mutant_enderman,96","mutantmore:mutant_blaze,96","
Can you commit and remove it?

2024-01-26 21:35 UTC, Jonah-Hansen approved these changes

2024-01-26 22:28 UTC, Jonah-Hansen commented
this last commit added manifest for oredict

2024-01-26 23:31 UTC, merged