Feature/villager trading
chocolate-edition/Chocolate-Edition pull request #344
Opened 2024-02-18 07:27 UTC by Huskykyle

progress for #249 and complete #247

2024-02-21 19:44 UTC, Jonah-Hansen requested changes
just some formatting fixes

please add indentation anywhere you open a bracket.

for example line 80-83 is good, but you need indentation on the others.
2 or 4 spaces doesn't really matter just be consistent. or just the `TAB` key on the keyboard.

2024-02-21 19:44 UTC, Jonah-Hansen commented on overrides/scripts/villager_trades_removed.zs
> +val toBuy = [<item:farmersdelight:barbecue_stick>,
things inside brackets should start on a new line, indented to show it is nested inside the brackets

so 
```js
val toBuy = [
  <item>
]
```

2024-02-21 19:44 UTC, Jonah-Hansen commented on overrides/scripts/villager_trades_removed.zs
> +{
you may see differing opinions but I always prefer opening brackets on same line. 

```js
for food in toBuy {
  // your code
}
```

2024-04-08 19:46 UTC, Jonah-Hansen commented
@GildedToxin so are we still wanting to add this?

2024-04-08 21:10 UTC, GildedToxin commented
Idk, I know @RichPrune wants villager stuff at somepoint so maybe just keep it here till then for reference? or is that bad pratice?

2024-04-08 21:14 UTC, Jonah-Hansen commented
imma just close it for now if we want the code we can still find it from this pr

2024-04-08 21:14 UTC, closed without merging