added ore stages for villager trading
chocolate-edition/Chocolate-Edition pull request #347
Opened 2024-02-19 05:19 UTC by GildedToxin

Add this mod! https://www.curseforge.com/minecraft/mc-mods/ore-stages-reborn

2024-02-21 19:45 UTC, Jonah-Hansen approved these changes

2024-02-21 19:46 UTC, Jonah-Hansen requested changes
if adding a mod please include the updated mod list and manifest

2024-02-21 19:51 UTC, GildedToxin commented
so true, forgot lol

2024-03-04 00:03 UTC, Jonah-Hansen requested changes

2024-03-04 00:03 UTC, Jonah-Hansen commented on modlist.html
mostlist is trying to add back goal optimizer and is not adding orestages mod. make sure its the right manifest and modlist

2024-03-04 00:47 UTC, Jonah-Hansen approved these changes

2024-03-04 00:48 UTC, merged